const MEDIAPIPE_URL='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14';
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm';
const MODEL='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task';
const $=id=>document.getElementById(id);
let PoseLandmarker,FilesetResolver,DrawingUtils,pose,stream,running=false,paused=false,raf,lastVideoTime=-1,phase='ready',count=0,lastTransition=0,loadPromise=null;
const cfg={
'floor-press':{kind:'elbowReverse',low:88,high:150,tip:'Prop the phone so your shoulders, elbows and wrists stay visible while lying down.'},
'shoulder-press':{kind:'wristY',up:-.08,down:.08,tip:'Face the camera and keep your head, shoulders and both wrists visible.'},
'chest-fly':{kind:'spread',up:.58,down:.34,tip:'Place the phone above and forward enough to see both shoulders and wrists.'},
'lateral-raise':{kind:'wristShoulder',up:.08,down:.23,tip:'Face the camera and keep your upper body and hands in frame.'},
'triceps-extension':{kind:'elbowReverse',low:78,high:150,tip:'Use a slight side view so your shoulder, elbow and wrist stay visible.'},
'wall-pushup':{kind:'elbowReverse',low:88,high:155,tip:'Place the phone side-on so your shoulder, elbow and wrist are visible.'},
'one-arm-row':{kind:'elbow',low:78,high:145,tip:'Use a side or three-quarter view of the working arm.'},
'pullover':{kind:'wristYReverse',up:-.13,down:.08,tip:'Prop the phone side-on or above so your shoulders and wrists remain visible.'},
'reverse-fly':{kind:'spread',up:.58,down:.36,tip:'Face the camera while hinged and keep both shoulders and hands visible.'},
'biceps-curl':{kind:'elbow',low:68,high:145,tip:'Face the camera at a slight angle and keep shoulder, elbow and wrist visible.'},
'hammer-curl':{kind:'elbow',low:68,high:145,tip:'Face the camera at a slight angle and keep the working arm visible.'},
'rear-delt-row':{kind:'elbow',low:82,high:145,tip:'Use a three-quarter view and keep shoulder, elbow and wrist visible.'}
};
const visible=p=>p&&((p.visibility??1)>.45);
function status(text,kind=''){const el=$('cameraStatus');if(!el)return;el.textContent=text;el.className='cameraStatus '+kind}
function angle(a,b,c){const abx=a.x-b.x,aby=a.y-b.y,cbx=c.x-b.x,cby=c.y-b.y;const den=Math.hypot(abx,aby)*Math.hypot(cbx,cby);if(!den)return 180;let v=(abx*cbx+aby*cby)/den;return Math.acos(Math.max(-1,Math.min(1,v)))*180/Math.PI}
function arm(l){const L=[l[11],l[13],l[15]],R=[l[12],l[14],l[16]];if(L.every(visible))return L;if(R.every(visible))return R;return null}
function metric(l,c){const a=arm(l);if(c.kind==='elbow'||c.kind==='elbowReverse')return a?angle(...a):null;if(![l[11],l[12],l[15],l[16]].every(visible))return null;const shY=(l[11].y+l[12].y)/2,wrY=(l[15].y+l[16].y)/2;if(c.kind==='wristY'||c.kind==='wristYReverse')return wrY-shY;if(c.kind==='wristShoulder')return Math.abs(wrY-shY);if(c.kind==='spread')return Math.abs(l[15].x-l[16].x);return null}
function states(v,c){if(c.kind==='elbow')return [v<c.low,v>c.high];if(c.kind==='elbowReverse')return [v>c.high,v<c.low];if(c.kind==='wristY')return [v<c.up,v>c.down];if(c.kind==='wristYReverse')return [v>c.down,v<c.up];if(c.kind==='wristShoulder')return [v<c.up,v>c.down];if(c.kind==='spread')return [v>c.up,v<c.down];return [false,false]}
function target(){return Number($('cameraTarget')?.value||0)}
function exercise(){return $('cameraExercise')?.value||''}
function updateCount(){const el=$('cameraCount');if(el)el.textContent=count}
function beep(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ac=new A(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=880;g.gain.value=.07;o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.08)}catch{}}
function rep(){count++;updateCount();beep();status(`Rep ${count} counted ✓`,'good');if(count>=target()&&target()>0){status('Set complete ✓','complete');pause();setTimeout(()=>window.dispatchEvent(new CustomEvent('strength:setComplete',{detail:{reps:count,exercise:exercise()}})),250)}}
function process(l){if(paused)return;const c=cfg[exercise()];if(!c)return;const v=metric(l,c);if(v==null){status('Move so the required joints are visible.','warn');return}const [peak,start]=states(v,c),now=performance.now();if(phase==='ready'&&start){phase='start';status('Ready — begin the movement.','good')}else if(phase==='start'&&peak&&now-lastTransition>250){phase='peak';lastTransition=now;status('Good range — return to the start.','good')}else if(phase==='peak'&&start&&now-lastTransition>250){phase='start';lastTransition=now;rep()}}
async function ensureMediaPipe(){if(pose)return;if(loadPromise)return loadPromise;loadPromise=(async()=>{status('Loading camera AI… this can take a few seconds the first time.');try{const vision=await import(MEDIAPIPE_URL);PoseLandmarker=vision.PoseLandmarker;FilesetResolver=vision.FilesetResolver;DrawingUtils=vision.DrawingUtils;if(!PoseLandmarker||!FilesetResolver)throw new Error('MediaPipe library did not expose the required pose tools.');const files=await FilesetResolver.forVisionTasks(WASM);pose=await PoseLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:MODEL,delegate:'GPU'},runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.55,minPosePresenceConfidence:.55,minTrackingConfidence:.55});status('Camera AI ready.','good')}catch(e){console.error('MediaPipe load failed',e);loadPromise=null;status('Camera AI failed to load. Check your internet connection and reload this page.','warn');throw e}})();return loadPromise}
async function start(){try{if(!navigator.mediaDevices?.getUserMedia){status('This browser does not provide camera access to web apps. Try Chrome or Samsung Internet updated to the latest version.','warn');return}await ensureMediaPipe();if(stream)stopTracks();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('cameraVideo');if(!v)throw new Error('Camera preview element is missing.');v.srcObject=stream;await v.play();running=true;paused=false;phase='ready';count=0;lastVideoTime=-1;updateCount();status('Camera active — move into the starting position.','good');loop()}catch(e){console.error('Camera start failed',e);if(e?.name==='NotAllowedError'||e?.name==='SecurityError')status('Camera permission was blocked. Allow camera access for this site, then try again.','warn');else if(e?.name==='NotFoundError')status('No usable front camera was found on this device.','warn');else if(!String(e?.message||'').includes('MediaPipe'))status('Could not start the camera. Reload the page and try again.','warn')}}
function stopTracks(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function stop(){running=false;paused=false;if(raf)cancelAnimationFrame(raf);raf=null;stopTracks();const v=$('cameraVideo');if(v)v.srcObject=null;status('Camera off.');}
function pause(){paused=true;status('Camera paused during rest.');}
function resumeSet(){count=0;phase='ready';lastTransition=0;updateCount();if(stream){paused=false;running=true;status('Camera ready for the next set.','good');loop()}else status('Camera off. Tap Use camera counter to start.');}
function reset(){count=0;phase='ready';lastTransition=0;updateCount();status(stream?'Counter reset — get into the starting position.':'Counter reset.');}
function adjust(delta){count=Math.max(0,Math.min(target()||999,count+delta));updateCount();status(`Rep count adjusted to ${count}.`,'good');if(count>=target()&&target()>0){pause();setTimeout(()=>window.dispatchEvent(new CustomEvent('strength:setComplete',{detail:{reps:count,exercise:exercise()}})),200)}}
function tip(id){return cfg[id]?.tip||'Keep your working joints clearly visible to the camera.'}
function drawPose(l){const cv=$('cameraOverlay'),v=$('cameraVideo');if(!cv||!v||!DrawingUtils)return;cv.width=v.videoWidth||640;cv.height=v.videoHeight||480;const ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);const d=new DrawingUtils(ctx);d.drawConnectors(l,PoseLandmarker.POSE_CONNECTIONS,{lineWidth:3});d.drawLandmarks(l,{radius:3})}
function loop(){if(!running||paused)return;const v=$('cameraVideo');if(!v||!pose){raf=requestAnimationFrame(loop);return}if(v.readyState>=2&&v.currentTime!==lastVideoTime){lastVideoTime=v.currentTime;try{pose.detectForVideo(v,performance.now(),r=>{const lm=r.landmarks?.[0];if(lm){drawPose(lm);process(lm)}else status('No person detected — step into view.','warn')})}catch(e){console.error('Pose frame error',e)}}raf=requestAnimationFrame(loop)}
window.StrengthCamera={start,stop,pause,resumeSet,reset,adjust,tip};
window.addEventListener('pagehide',stop);